/**
 * Recipe scale control (⅓ ½ 1× 2× 3×) for recipe pages.
 *
 * Unlike the units toggle, the scaled amounts can't all be baked into the HTML, so this module
 * rewrites amount text. It never reads the text it replaces: every amount that can scale
 * carries its authored values as data attributes (`data-qty` + `data-unit` on the US amount,
 * `data-grams` on the grams one, `data-servings` on the Serves value), and each rewrite is
 * computed from those — so applying a factor twice, or going back to 1×, is exact.
 *
 * The same amount appears in the ingredient list, in the step popovers and in the inline step
 * copies; all three carry the attributes and all three are rewritten together. Which of US or
 * grams is *shown* stays the units toggle's business (CSS on `data-units`).
 *
 * The choice is deliberately not stored: a recipe always opens as written.
 *
 * Styling is entirely `aria-pressed` (the control is a Dizzy `.dz-seg`), plus `data-scale` on
 * <html> for the "step text isn't scaled" note — this module never touches a class.
 */
import { SCALE_FACTORS, formatQty, scaleQty } from '../scale';
import { UNICODE_FRACTIONS, formatGrams } from '../units';

const ORIGINAL = '1';

/**
 * Set an amount's text. Amounts generated by src/ingredients.ts (inside `.ing-amt`) wrap each
 * fraction glyph in `.ing-frac` so it draws full-size in the mono face; the ingredient list
 * doesn't. Rebuild whichever shape the element was baked with.
 */
function setAmountText(el: Element, text: string): void {
  if (!el.closest('.ing-amt')) {
    el.textContent = text;
    return;
  }
  const nodes: (Node | string)[] = [];
  let run = '';
  for (const ch of text) {
    if (ch in UNICODE_FRACTIONS) {
      if (run) nodes.push(run);
      run = '';
      const frac = document.createElement('span');
      frac.className = 'ing-frac';
      frac.textContent = ch;
      nodes.push(frac);
    } else {
      run += ch;
    }
  }
  if (run) nodes.push(run);
  el.replaceChildren(...nodes);
}

/** Rewrite every scalable amount under `root` for the factor with this id (unknown → 1×). */
export function applyScale(id: string, root: ParentNode = document): void {
  const factor = SCALE_FACTORS.find((f) => f.id === id) ?? SCALE_FACTORS.find((f) => f.id === ORIGINAL)!;
  const scaled = factor.id !== ORIGINAL;

  for (const el of root.querySelectorAll<HTMLElement>('[data-qty]')) {
    const qty = scaleQty(el.dataset.qty ?? '', factor.value);
    setAmountText(el, [qty, el.dataset.unit].filter(Boolean).join(' '));
  }

  for (const el of root.querySelectorAll<HTMLElement>('[data-grams]')) {
    const grams = Number(el.dataset.grams);
    if (Number.isFinite(grams)) el.textContent = formatGrams(grams * factor.value);
  }

  for (const el of root.querySelectorAll<HTMLElement>('[data-servings]')) {
    const servings = Number(el.dataset.servings);
    if (Number.isFinite(servings)) el.textContent = formatQty(servings * factor.value) || String(servings);
  }

  for (const el of root.querySelectorAll<HTMLElement>('[data-scale-status]')) {
    el.textContent = scaled ? `Amounts scaled to ${factor.label}.` : '';
  }

  if (scaled) document.documentElement.dataset.scale = factor.id;
  else delete document.documentElement.dataset.scale;
}

export function initRecipeScale(): void {
  const buttons = Array.from(
    document.querySelectorAll<HTMLButtonElement>('[data-scale-control] [data-scale-btn]')
  );
  if (buttons.length === 0) return;

  // The page is baked at 1× with that button pressed, so nothing is applied until a choice.
  const choose = (id: string) => {
    applyScale(id);
    for (const btn of buttons) btn.setAttribute('aria-pressed', String(btn.dataset.scaleBtn === id));
  };

  for (const btn of buttons) {
    btn.addEventListener('click', () => choose(btn.dataset.scaleBtn ?? ORIGINAL));
    // Left/Right move to the neighbouring option within the same control and select it, the
    // segmented-control convention (matches recipe-units.ts).
    btn.addEventListener('keydown', (event) => {
      const step = event.key === 'ArrowRight' ? 1 : event.key === 'ArrowLeft' ? -1 : 0;
      if (!step) return;
      const group = Array.from(
        btn.closest('[data-scale-control]')?.querySelectorAll<HTMLButtonElement>('[data-scale-btn]') ?? []
      );
      const next = group[(group.indexOf(btn) + step + group.length) % group.length];
      if (!next) return;
      event.preventDefault();
      next.focus();
      choose(next.dataset.scaleBtn ?? ORIGINAL);
    });
  }
}
